// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// Check for compatibility between `uniffi` and `uniffi_bindgen` versions.
// Note that we have an error message on the same line as the assertion.
// This is important, because if the assertion fails, the compiler only
// seems to show that single line as context for the user.
uniffi::assert_compatible_version!("0.17.0"); // Please check that you depend on version 0.17.0 of the `uniffi` crate.

// Everybody gets basic buffer support, since it's needed for passing complex types over the FFI.

/// This helper allocates a new byte buffer owned by the Rust code, and returns it
/// to the foreign-language code as a `RustBuffer` struct. Callers must eventually
/// free the resulting buffer, either by explicitly calling the destructor defined below,
/// or by passing ownership of the buffer back into Rust code.
#[doc(hidden)]
#[no_mangle]
pub extern "C" fn ffi_rocketscience_b310_rustbuffer_alloc(
    size: i32,
    call_status: &mut uniffi::RustCallStatus,
) -> uniffi::RustBuffer {
    uniffi::call_with_output(call_status, || {
        uniffi::RustBuffer::new_with_size(size.max(0) as usize)
    })
}

/// This helper copies bytes owned by the foreign-language code into a new byte buffer owned
/// by the Rust code, and returns it as a `RustBuffer` struct. Callers must eventually
/// free the resulting buffer, either by explicitly calling the destructor defined below,
/// or by passing ownership of the buffer back into Rust code.
///
/// # Safety
/// This function will dereference a provided pointer in order to copy bytes from it, so
/// make sure the `ForeignBytes` struct contains a valid pointer and length.
#[doc(hidden)]
#[no_mangle]
pub unsafe extern "C" fn ffi_rocketscience_b310_rustbuffer_from_bytes(
    bytes: uniffi::ForeignBytes,
    call_status: &mut uniffi::RustCallStatus,
) -> uniffi::RustBuffer {
    uniffi::call_with_output(call_status, || {
        let bytes = bytes.as_slice();
        uniffi::RustBuffer::from_vec(bytes.to_vec())
    })
}

/// Free a byte buffer that had previously been passed to the foreign language code.
///
/// # Safety
/// The argument *must* be a uniquely-owned `RustBuffer` previously obtained from a call
/// into the Rust code that returned a buffer, or you'll risk freeing unowned memory or
/// corrupting the allocator state.
#[doc(hidden)]
#[no_mangle]
pub unsafe extern "C" fn ffi_rocketscience_b310_rustbuffer_free(
    buf: uniffi::RustBuffer,
    call_status: &mut uniffi::RustCallStatus,
) {
    uniffi::call_with_output(call_status, || uniffi::RustBuffer::destroy(buf))
}

/// Reserve additional capacity in a byte buffer that had previously been passed to the
/// foreign language code.
///
/// The first argument *must* be a uniquely-owned `RustBuffer` previously
/// obtained from a call into the Rust code that returned a buffer. Its underlying data pointer
/// will be reallocated if necessary and returned in a new `RustBuffer` struct.
///
/// The second argument must be the minimum number of *additional* bytes to reserve
/// capacity for in the buffer; it is likely to reserve additional capacity in practice
/// due to amortized growth strategy of Rust vectors.
///
/// # Safety
/// The first argument *must* be a uniquely-owned `RustBuffer` previously obtained from a call
/// into the Rust code that returned a buffer, or you'll risk freeing unowned memory or
/// corrupting the allocator state.
#[doc(hidden)]
#[no_mangle]
pub unsafe extern "C" fn ffi_rocketscience_b310_rustbuffer_reserve(
    buf: uniffi::RustBuffer,
    additional: i32,
    call_status: &mut uniffi::RustCallStatus,
) -> uniffi::RustBuffer {
    uniffi::call_with_output(call_status, || {
        use std::convert::TryInto;
        let additional: usize = additional
            .try_into()
            .expect("additional buffer length negative or overflowed");
        let mut v = buf.destroy_into_vec();
        v.reserve(additional);
        uniffi::RustBuffer::from_vec(v)
    })
}

// Error definitions, corresponding to `error` in the UDL.

#[doc(hidden)]
pub struct FfiConverterTypeLaunchError;

#[doc(hidden)]
impl uniffi::RustBufferFfiConverter for FfiConverterTypeLaunchError {
    type RustType = LaunchError;

    // For "flat" error enums, we stringify the error on the Rust side and surface that
    // as the error message in the foreign language.

    fn write(obj: LaunchError, buf: &mut std::vec::Vec<u8>) {
        use uniffi::deps::bytes::BufMut;
        let msg = obj.to_string();
        match obj {
            LaunchError::RocketLaunch { .. } => {
                buf.put_i32(1);
                <String as uniffi::FfiConverter>::write(msg, buf);
            }
        };
    }

    fn try_read(_buf: &mut &[u8]) -> uniffi::deps::anyhow::Result<LaunchError> {
        // It's not currently possible to send errors from the foreign language *into* Rust.
        panic!("try_read not supported for flat errors");
    }
}

impl uniffi::FfiError for FfiConverterTypeLaunchError {}

// Enum defitions, corresponding to `enum` in UDL.

#[doc(hidden)]
pub struct FfiConverterTypeDirection;

#[doc(hidden)]
impl uniffi::RustBufferFfiConverter for FfiConverterTypeDirection {
    type RustType = Direction;

    fn write(obj: Self::RustType, buf: &mut std::vec::Vec<u8>) {
        use uniffi::deps::bytes::BufMut;
        match obj {
            Direction::Up {} => {
                buf.put_i32(1);
            }
            Direction::Down {} => {
                buf.put_i32(2);
            }
        };
    }

    fn try_read(buf: &mut &[u8]) -> uniffi::deps::anyhow::Result<Direction> {
        use uniffi::deps::bytes::Buf;
        uniffi::check_remaining(buf, 4)?;
        Ok(match buf.get_i32() {
            1 => Direction::Up,
            2 => Direction::Down,
            v => uniffi::deps::anyhow::bail!("Invalid Direction enum value: {}", v),
        })
    }
}

// Record definitions, implemented as method-less structs, corresponding to `dictionary` objects.

#[doc(hidden)]
pub struct FfiConverterTypePart;

#[doc(hidden)]
impl uniffi::RustBufferFfiConverter for FfiConverterTypePart {
    type RustType = Part;

    fn write(obj: Part, buf: &mut std::vec::Vec<u8>) {
        // If the provided struct doesn't match the fields declared in the UDL, then
        // the generated code here will fail to compile with somewhat helpful error.
        <String as uniffi::FfiConverter>::write(obj.name, buf);
        <u64 as uniffi::FfiConverter>::write(obj.cost, buf);
        <u64 as uniffi::FfiConverter>::write(obj.weight, buf);
    }

    fn try_read(buf: &mut &[u8]) -> uniffi::deps::anyhow::Result<Part> {
        Ok(Part {
            name: <String as uniffi::FfiConverter>::try_read(buf)?,
            cost: <u64 as uniffi::FfiConverter>::try_read(buf)?,
            weight: <u64 as uniffi::FfiConverter>::try_read(buf)?,
        })
    }
}

// Top level functions, corresponding to UDL `namespace` functions.// Object definitions, corresponding to UDL `interface` definitions.

// For each Object definition, we assume the caller has provided an appropriately-shaped `struct T`
// with an `impl` for each method on the object. We create an `Arc<T>` for "safely" handing out
// references to these structs to foreign language code, and we provide a `pub extern "C"` function
// corresponding to each method.
//
// (Note that "safely" is in "scare quotes" - that's because we use functions on an `Arc` that
// that are inherently unsafe, but the code we generate is safe in practice.)
//
// If the caller's implementation of the struct does not match with the methods or types specified
// in the UDL, then the rust compiler will complain with a (hopefully at least somewhat helpful!)
// error message when processing this generated code.

// All Object structs must be `Sync + Send`. The generated scaffolding will fail to compile
// if they are not, but unfortunately it fails with an unactionably obscure error message.
// By asserting the requirement explicitly, we help Rust produce a more scrutable error message
// and thus help the user debug why the requirement isn't being met.
uniffi::deps::static_assertions::assert_impl_all!(Rocket: Sync, Send);

#[doc(hidden)]
#[no_mangle]
pub extern "C" fn ffi_rocketscience_b310_Rocket_object_free(
    ptr: *const std::os::raw::c_void,
    call_status: &mut uniffi::RustCallStatus,
) {
    uniffi::call_with_output(call_status, || {
        assert!(!ptr.is_null());
        drop(unsafe { std::sync::Arc::from_raw(ptr as *const Rocket) })
    })
}
#[doc(hidden)]
#[no_mangle]
pub extern "C" fn rocketscience_b310_Rocket_new(
    name: uniffi::RustBuffer,
    call_status: &mut uniffi::RustCallStatus,
) -> *const std::os::raw::c_void /* *const Rocket */ {
    uniffi::deps::log::debug!("rocketscience_b310_Rocket_new");

    // If the constructor does not have the same signature as declared in the UDL, then
    // this attempt to call it will fail with a (somewhat) helpful compiler error.

    uniffi::call_with_output(call_status, || {
        let _new = Rocket::new(match <String as uniffi::FfiConverter>::try_lift(name) {
            Ok(val) => val,

            Err(err) => panic!("Failed to convert arg '{}': {}", "name", err),
        });
        let _arc = std::sync::Arc::new(_new);
        <std::sync::Arc<Rocket> as uniffi::FfiConverter>::lower(_arc)
    })
}
#[doc(hidden)]
#[no_mangle]
pub extern "C" fn rocketscience_b310_Rocket_show(
    ptr: *const std::os::raw::c_void,
    call_status: &mut uniffi::RustCallStatus,
) -> uniffi::RustBuffer {
    uniffi::deps::log::debug!("rocketscience_b310_Rocket_show");
    // If the method does not have the same signature as declared in the UDL, then
    // this attempt to call it will fail with a (somewhat) helpful compiler error.

    uniffi::call_with_output(call_status, || {
        let retval = Rocket::show(
            match <std::sync::Arc<Rocket> as uniffi::FfiConverter>::try_lift(ptr) {
                Ok(ref val) => val,

                Err(err) => panic!("Failed to convert arg '{}': {}", "ptr", err),
            },
        );
        <String as uniffi::FfiConverter>::lower(retval)
    })
}

#[doc(hidden)]
#[no_mangle]
pub extern "C" fn rocketscience_b310_Rocket_launch(
    ptr: *const std::os::raw::c_void,
    call_status: &mut uniffi::RustCallStatus,
) -> i8 {
    uniffi::deps::log::debug!("rocketscience_b310_Rocket_launch");
    // If the method does not have the same signature as declared in the UDL, then
    // this attempt to call it will fail with a (somewhat) helpful compiler error.

    uniffi::call_with_result(call_status, || {
        let _retval = Rocket::launch(
            match <std::sync::Arc<Rocket> as uniffi::FfiConverter>::try_lift(ptr) {
                Ok(ref val) => val,

                Err(err) => {
                    return Err(uniffi::lower_anyhow_error_or_panic::<
                        FfiConverterTypeLaunchError,
                    >(err, "ptr"))
                }
            },
        )
        .map_err(Into::into)
        .map_err(<FfiConverterTypeLaunchError as uniffi::FfiConverter>::lower)?;
        Ok(<bool as uniffi::FfiConverter>::lower(_retval))
    })
}

#[doc(hidden)]
#[no_mangle]
pub extern "C" fn rocketscience_b310_Rocket_add(
    ptr: *const std::os::raw::c_void,
    part: uniffi::RustBuffer,
    call_status: &mut uniffi::RustCallStatus,
) {
    uniffi::deps::log::debug!("rocketscience_b310_Rocket_add");
    // If the method does not have the same signature as declared in the UDL, then
    // this attempt to call it will fail with a (somewhat) helpful compiler error.

    uniffi::call_with_output(call_status, || {
        Rocket::add(
            match <std::sync::Arc<Rocket> as uniffi::FfiConverter>::try_lift(ptr) {
                Ok(ref val) => val,

                Err(err) => panic!("Failed to convert arg '{}': {}", "ptr", err),
            },
            match <FfiConverterTypePart as uniffi::FfiConverter>::try_lift(part) {
                Ok(val) => val,

                Err(err) => panic!("Failed to convert arg '{}': {}", "part", err),
            },
        )
    })
}

#[doc(hidden)]
#[no_mangle]
pub extern "C" fn rocketscience_b310_Rocket_lock_steering(
    ptr: *const std::os::raw::c_void,
    direction: uniffi::RustBuffer,
    call_status: &mut uniffi::RustCallStatus,
) {
    uniffi::deps::log::debug!("rocketscience_b310_Rocket_lock_steering");
    // If the method does not have the same signature as declared in the UDL, then
    // this attempt to call it will fail with a (somewhat) helpful compiler error.

    uniffi::call_with_output(call_status, || {
        Rocket::lock_steering(
            match <std::sync::Arc<Rocket> as uniffi::FfiConverter>::try_lift(ptr) {
                Ok(ref val) => val,

                Err(err) => panic!("Failed to convert arg '{}': {}", "ptr", err),
            },
            match <FfiConverterTypeDirection as uniffi::FfiConverter>::try_lift(direction) {
                Ok(val) => val,

                Err(err) => panic!("Failed to convert arg '{}': {}", "direction", err),
            },
        )
    })
}

// Callback Interface definitions, corresponding to UDL `callback interface` definitions.

// External and Wrapped types
// Support for external types.

// Types with an external `FfiConverter`...

// For custom scaffolding types we need to generate an FfiConverterType based on the
// UniffiCustomTypeConverter implementation that the library supplies
