name: CI
on:
  pull_request:
  push:
    branches: [main]

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  CI: 1
  RUST_BACKTRACE: short
  RUSTFLAGS: -D warnings
  RUSTUP_MAX_RETRIES: 10

jobs:
  test:
    name: test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        components: rustfmt
        override: true
    - uses: Swatinem/rust-cache@v1

    - name: Test Python
      if: matrix.os == 'ubuntu-latest'
      run: cargo xtask test python

    - name: Test Kotlin
      if: matrix.os == 'ubuntu-latest'
      run: |
        curl -o jna.jar https://repo1.maven.org/maven2/net/java/dev/jna/jna/5.8.0/jna-5.8.0.jar
        export CLASSPATH="$CLASSPATH:$(pwd)/jna.jar"
        cargo xtask test kotlin

    - name: Test Swift
      if: matrix.os == 'macos-latest'
      run: cargo xtask test swift
